name: Feature request
description: Suggest a new idea or enhancement for Bereznev HY2 Core
title: "feat: "
labels: [type:feature, area:core]
body:
  - type: textarea
    attributes:
      label: What feature would you like to see?
      placeholder: Describe your idea clearly…
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this feature important?
      placeholder: Explain the problem it solves or what it improves…

  - type: textarea
    attributes:
      label: Additional context or screenshots
      placeholder: Add mockups, configs, or use-cases if relevant