name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Go tests (core-go/mobile)
        working-directory: core-go/mobile
        run: |
          echo "🏗️ Running Go vet/tests with tag mobile_skel..."
          go vet -tags=mobile_skel ./...              # <- добавили тэг
          go test -tags=mobile_skel -v ./... -timeout=5m -mod=readonly
          echo "✅ Go tests passed successfully"