name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install gomobile toolchain
        run: |
          # Устанавливаем gomobile/gobind (с кешированием в GOPATH/bin)
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          # Инициализация окружения только если не инициализировано ранее
          if [ ! -d "$HOME/go/pkg/mod/golang.org/x/mobile" ]; then
            gomobile init
          else
            echo "gomobile already initialized"
          fi
        env:
          PATH: ${{ env.PATH }}:$HOME/go/bin

      - name: Run Go tests (core-go)
        run: |
          cd core-go/mobile
          echo "🏗️ Running Go tests with tag mobile_skel..."
          go vet ./...            # линтер на всякий случай
          go test -tags=mobile_skel -v ./... -timeout=5m
          echo "✅ Go tests passed successfully"

      