name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      - name: Build AAR (Android)
        run: |
          cd core-go/mobile
          gomobile bind -target=android -o BereznevHY2.aar

      - name: Build XCFramework (iOS)
        run: |
          cd core-go/mobile
          gomobile bind -target=ios -o BereznevHY2.xcframework.zip

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            core-go/mobile/BereznevHY2.aar
            core-go/mobile/BereznevHY2.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}